Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,6 +36,18 @@ jobs:
         working-directory: ./db-infra
         run: terraform validate
 
+      - name: Delete DB Subnet Group if exists
+        working-directory: ./db-infra
+        run: |
+          echo "Checking if DB Subnet Group exists..."
+          EXISTING_SUBNET_GROUP=$(aws rds describe-db-subnet-groups --query "DBSubnetGroups[?DBSubnetGroupName=='rds-subnet-group']" --output text)
+          if [ "$EXISTING_SUBNET_GROUP" != "None" ]; then
+            echo "DB Subnet Group exists, deleting it..."
+            aws rds delete-db-subnet-group --db-subnet-group-name rds-subnet-group || echo "Error deleting DB Subnet Group, it might not exist"
+          else
+            echo "DB Subnet Group does not exist, skipping deletion."
+          fi
+
       - name: Terraform Plan with Debug Logs
         working-directory: ./db-infra
         run: |
@@ -45,7 +57,7 @@ jobs:
             -var="eks_private_cidrs=${{ secrets.EKS_PRIVATE_CIDRS }}" \
             -var="db_username=${{ secrets.POSTGRES_USER }}" \
             -var="db_password=${{ secrets.POSTGRES_PASSWORD}}"
-
+      
       - name: Terraform Apply with Debug Logs
         working-directory: ./db-infra
         run: |
